# For more information on how to use this template please refer to:
# http://tardis-sn.github.io/tardis/development/continuous_integration.html

# Testing Tags 1

name: changelog

on: 
  push:
    tags:
      - 'release-**'

# workflow_dispatch:  # Manual trigger

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v2
        with:
          repository: rohithvarma3000/tardis
          fetch-depth: 0

      - name: Install github-changes
        run: sudo npm install -g github-changes

      - name: Update changelog
        run: github-changes -o tardis-sn -r tardis --only-pulls --use-commit-body -f CHANGELOG.md -k ${{ secrets.GITHUB_TOKEN }}

      - name: Configure bot user
        run: |
          git config --global user.email "tardis.sn.bot@gmail.com"
          git config --global user.name "tardis-bot"

      - name: Push changes
        run: |
          git add CHANGELOG.md
          git commit --amend --no-edit
          GIT_TAG_MESSAGE=$(git tag -l --format='%(contents)' ${{ github.ref_name }})
          git tag -d ${{ github.ref_name }}
          git tag -a ${{ github.ref_name }} -m "$GIT_TAG_MESSAGE"
          git checkout master
          git push origin :${{ github.ref_name }}
          git push
